#introduction to tensors

In [2]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [4]:
scalar = tf.constant(7)

In [5]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
vector = tf.constant([10,10])

In [7]:
vector.ndim

1

In [8]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
matrix = tf.constant([[10,10],[7,10]])

In [10]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7, 10]], dtype=int32)>

In [13]:
matrix2 = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)

In [14]:
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

### Create variable tensor

In [19]:
v = tf.Variable([1.,2.,4.])

In [20]:
v

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 4.], dtype=float32)>

In [23]:
v[0].assign(10.)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([10.,  2.,  4.], dtype=float32)>

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([10.,  2.,  4.], dtype=float32)>

### Random Tensor

In [25]:
random_1 = tf.random.Generator.from_seed(42)
random_2 = random_1.normal(shape=(3,2))

In [26]:
random_2 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### shuffle a tensor

In [29]:
not_shaffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

In [30]:
not_shaffled.ndim

2

In [32]:
tf.random.shuffle(not_shaffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [33]:
not_shaffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [39]:
tf.random.set_seed(1234)

In [40]:
print(tf.random.uniform([1])) 

tf.Tensor([0.5380393], shape=(1,), dtype=float32)


In [41]:
print(tf.random.uniform([1]))

tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [43]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [45]:
tf.ones((20,3))

<tf.Tensor: shape=(20, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [46]:
tf.zeros([2,5])

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [50]:
tf.range([10])

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [53]:
import numpy as np
A = np.arange(1,25)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [57]:
B = tf.constant(A,shape=(2,3,4))

In [55]:
B

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [61]:
B

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### Getting imformation from tensor

In [64]:
rank_4 = tf.zeros(shape=(2,3,4,5))

In [65]:
rank_4.shape

TensorShape([2, 3, 4, 5])

In [67]:
B.numpy()

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### indexing tensors

In [71]:
B[:2,:2]

<tf.Tensor: shape=(2, 2, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20]]])>

### Get the first dimensions

### adding dimmenstion

In [74]:
 A = A[...,tf.newaxis]

In [75]:
A.shape

(24, 1)

### alternative to tf.newaxis

In [77]:
tf.expand_dims(A,axis=2).shape

TensorShape([24, 1, 1])

## Tensor operations

In [81]:
tensor = tf.constant([[10,7],[3,4]])

In [82]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [83]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [84]:
tf.multiply(tensor,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 140],
       [ 60,  80]], dtype=int32)>

### Matrix maltiplications

In [91]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [97]:
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [87]:
X = tf.constant([[1,2],[3,4],[5,6]])

In [88]:
Y = tf.constant([[7,8],[9,10],[11,12]])

In [94]:
tf.reshape(Y,shape=(2,-1))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [96]:
X@tf.reshape(Y,shape=(2,-1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [98]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [100]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [101]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

### Changing datatype

In [102]:
B = tf.constant([1.7,7.4])

In [103]:
C = tf.constant([7,10])

In [106]:
B.dtype,C.dtype

(tf.float32, tf.int32)

In [107]:
tf.cast(B,dtype=tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [108]:
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>

### Aggregation

In [109]:
D = tf.constant([-7,-10])

In [110]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [113]:
E = tf.constant(np.random.randint(0,100,size=50))

In [115]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [116]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [118]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=38>

In [119]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1911>

In [134]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.856266>

In [127]:
import tensorflow_probability as tfp

In [128]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=776>

In [138]:
 F = tf.random.uniform(shape=[50])

In [139]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

### Squeeaing a tensor

In [142]:
tf.random.set_seed(42)
G = tf.constant( tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))

In [143]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [148]:
G_squeezed = tf.squeeze(G)

In [149]:
some_list = [0,1,2,3]

In [153]:
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Saquaring,log and root

In [154]:
H = tf.range(1,10)

In [155]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [157]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [160]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [164]:
tf.config.list_physical_devices("TPU")

[]