In [3]:
import numpy as np

In [4]:
k = np.random.rand(5,6)
k

array([[0.9551644 , 0.78923207, 0.3005305 , 0.31572148, 0.04470953,
        0.99088357],
       [0.23920468, 0.23277484, 0.23548914, 0.69818683, 0.47977751,
        0.28024939],
       [0.38732033, 0.85757761, 0.79754586, 0.60858022, 0.76796752,
        0.43765818],
       [0.48339716, 0.05896535, 0.7564685 , 0.66282285, 0.84979974,
        0.49680314],
       [0.87652597, 0.4121325 , 0.52816861, 0.52018772, 0.42625831,
        0.74464119]])

In [5]:
k.flatten()

array([0.9551644 , 0.78923207, 0.3005305 , 0.31572148, 0.04470953,
       0.99088357, 0.23920468, 0.23277484, 0.23548914, 0.69818683,
       0.47977751, 0.28024939, 0.38732033, 0.85757761, 0.79754586,
       0.60858022, 0.76796752, 0.43765818, 0.48339716, 0.05896535,
       0.7564685 , 0.66282285, 0.84979974, 0.49680314, 0.87652597,
       0.4121325 , 0.52816861, 0.52018772, 0.42625831, 0.74464119])

In [6]:
k.flatten("F")

array([0.9551644 , 0.23920468, 0.38732033, 0.48339716, 0.87652597,
       0.78923207, 0.23277484, 0.85757761, 0.05896535, 0.4121325 ,
       0.3005305 , 0.23548914, 0.79754586, 0.7564685 , 0.52816861,
       0.31572148, 0.69818683, 0.60858022, 0.66282285, 0.52018772,
       0.04470953, 0.47977751, 0.76796752, 0.84979974, 0.42625831,
       0.99088357, 0.28024939, 0.43765818, 0.49680314, 0.74464119])

In [7]:
k.ravel()

array([0.9551644 , 0.78923207, 0.3005305 , 0.31572148, 0.04470953,
       0.99088357, 0.23920468, 0.23277484, 0.23548914, 0.69818683,
       0.47977751, 0.28024939, 0.38732033, 0.85757761, 0.79754586,
       0.60858022, 0.76796752, 0.43765818, 0.48339716, 0.05896535,
       0.7564685 , 0.66282285, 0.84979974, 0.49680314, 0.87652597,
       0.4121325 , 0.52816861, 0.52018772, 0.42625831, 0.74464119])

In [8]:
k.reshape(-1)

array([0.9551644 , 0.78923207, 0.3005305 , 0.31572148, 0.04470953,
       0.99088357, 0.23920468, 0.23277484, 0.23548914, 0.69818683,
       0.47977751, 0.28024939, 0.38732033, 0.85757761, 0.79754586,
       0.60858022, 0.76796752, 0.43765818, 0.48339716, 0.05896535,
       0.7564685 , 0.66282285, 0.84979974, 0.49680314, 0.87652597,
       0.4121325 , 0.52816861, 0.52018772, 0.42625831, 0.74464119])

In [9]:
k

array([[0.9551644 , 0.78923207, 0.3005305 , 0.31572148, 0.04470953,
        0.99088357],
       [0.23920468, 0.23277484, 0.23548914, 0.69818683, 0.47977751,
        0.28024939],
       [0.38732033, 0.85757761, 0.79754586, 0.60858022, 0.76796752,
        0.43765818],
       [0.48339716, 0.05896535, 0.7564685 , 0.66282285, 0.84979974,
        0.49680314],
       [0.87652597, 0.4121325 , 0.52816861, 0.52018772, 0.42625831,
        0.74464119]])

In [10]:
lt_array = np.array([[1,3],"0",[6,6]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [11]:
cop = np.copy(lt_array)

In [12]:
cop[0][0] = 10

In [13]:
print(lt_array)

[list([10, 3]) '0' list([6, 6])]


In [14]:
print(cop)

[list([10, 3]) '0' list([6, 6])]


In [15]:
arr = np.random.rand(4,1,5)

In [16]:
arr

array([[[8.44881944e-02, 6.50834212e-01, 3.71064393e-01, 1.53577403e-04,
         1.61021959e-01]],

       [[8.92674420e-02, 1.29327500e-01, 8.34394879e-01, 6.24704812e-01,
         1.36347893e-01]],

       [[8.47005548e-01, 2.56338235e-01, 8.32595258e-01, 7.94702008e-02,
         5.02715543e-01]],

       [[2.72222402e-01, 3.69950214e-02, 5.02695769e-01, 7.45819665e-01,
         6.85029950e-01]]])

In [17]:
arrs = arr.squeeze()

In [18]:
arrs

array([[8.44881944e-02, 6.50834212e-01, 3.71064393e-01, 1.53577403e-04,
        1.61021959e-01],
       [8.92674420e-02, 1.29327500e-01, 8.34394879e-01, 6.24704812e-01,
        1.36347893e-01],
       [8.47005548e-01, 2.56338235e-01, 8.32595258e-01, 7.94702008e-02,
        5.02715543e-01],
       [2.72222402e-01, 3.69950214e-02, 5.02695769e-01, 7.45819665e-01,
        6.85029950e-01]])

In [19]:
arr2 = np.random.rand(1,4,1,5)

In [20]:
arr2.squeeze()

array([[0.08369562, 0.9512198 , 0.63048926, 0.39011806, 0.8900254 ],
       [0.03808703, 0.7226354 , 0.46747615, 0.40423082, 0.88399298],
       [0.70392083, 0.85676863, 0.84967836, 0.79141026, 0.9286444 ],
       [0.7358223 , 0.61663481, 0.70906327, 0.51428853, 0.87699204]])

In [21]:
arr2.squeeze(axis=2)

array([[[0.08369562, 0.9512198 , 0.63048926, 0.39011806, 0.8900254 ],
        [0.03808703, 0.7226354 , 0.46747615, 0.40423082, 0.88399298],
        [0.70392083, 0.85676863, 0.84967836, 0.79141026, 0.9286444 ],
        [0.7358223 , 0.61663481, 0.70906327, 0.51428853, 0.87699204]]])

In [22]:
my_arr = np.arange(10)

In [23]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.expand_dims(my_arr,axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [25]:
arr = np.array([[1,2],[3,4]])
arr2 = np.array([[6,4]])

In [26]:
np.concatenate([arr,arr2],axis=0)

array([[1, 2],
       [3, 4],
       [6, 4]])

In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [28]:
np.stack((arr1,arr2),axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
a = np.array([1,2,3])

In [30]:
b = np.array([4,5,6])

In [31]:
a = np.arange(60.).reshape(3,4,5)

b = np.arange(24.).reshape(4,3,2)

In [32]:
z = np.tensordot(a,b,axes=((0),(1)))
z.shape

(4, 5, 4, 2)

In [33]:
c = np.tensordot(a,b, axes=([1,0],[0,1]))

In [34]:
c

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [35]:
A = np.random.randint(2, size=(2, 6, 5))
B = np.random.randint(2, size=(3, 2, 4))

In [36]:
A.shape

(2, 6, 5)

In [37]:
B.shape

(3, 2, 4)

In [38]:
np.tensordot(B, A, axes=((1),(0))).shape

(3, 4, 6, 5)

In [39]:
import torch

In [40]:
torch.tensor([1,3,4]).type(torch.float32)

tensor([1., 3., 4.])

In [41]:
t = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
t

tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]])

In [42]:
a = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(torch.transpose(a,0,1))
print(a)

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [43]:
t

tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]])

In [44]:
t.transpose(0,1)

tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  9,  10,  11,  12],
         [ -9, -10, -11, -12]]])

In [45]:
t.numpy().transpose()

array([[[  1,  -1],
        [  5,  -5],
        [  9,  -9]],

       [[  2,  -2],
        [  6,  -6],
        [ 10, -10]],

       [[  3,  -3],
        [  7,  -7],
        [ 11, -11]],

       [[  4,  -4],
        [  8,  -8],
        [ 12, -12]]])

In [47]:
from google.colab import drive

In [50]:
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [62]:
!pip install kaggle
!mkdir .kaggle
%cd /content/.kaggle

mkdir: cannot create directory ‘.kaggle’: File exists
/content/.kaggle


In [65]:
import json

token = {"username":"faustino2020","key":"318c5611eb866a9e57e7183721d4ff2b"}
with open("/content/.kaggle/kaggle.json","w") as file:
  json.dump(token, file)

In [67]:
!chmod 600 /content/.kaggle/kaggle.json
!cp /content/.kaggle/kaggle.json /root/.kaggle/
!kaggle config set -n path -v /content

- path is now set to: /content


In [68]:
!kaggle competitions download -c 11-785-fall-21-intro-to-colab

403 - Forbidden


In [69]:
!pip install --upgrade --force-reinstall --no-deps kaggle

     |████████████████████████████████| 58 kB 3.4 MB/s 
  Created wheel for kaggle: filename=kaggle-1.5.12-py3-none-any.whl size=73051 sha256=f004d5cff99ae0d181ed315161cd3696c29a151fe556ab870d7501f405863934
  Stored in directory: /root/.cache/pip/wheels/62/d6/58/5853130f941e75b2177d281eb7e44b4a98ed46dd155f556dc5
Successfully built kaggle
  Attempting uninstall: kaggle
    Found existing installation: kaggle 1.5.12
    Uninstalling kaggle-1.5.12:
      Successfully uninstalled kaggle-1.5.12


In [71]:
!kaggle competitions download -c 11-785-fall-21-intro-to-colab


  0% 0.00/374 [00:00<?, ?B/s]
100% 374/374 [00:00<00:00, 171kB/s]


In [74]:
%pwd

'/content/.kaggle'

In [76]:
!kaggle competitions submit -c 11-785-fall-21-intro-to-colab -f /content/competitions/11-785-fall-21-intro-to-colab/11-785-fall-21-intro-to-colab.zip -m "submit"

100% 374/374 [00:01<00:00, 222B/s]
Successfully submitted to 11-785 Fall 21 Intro-to-Colab